authors:
  Chachalingo:
    name: Santiago Acuña González      # Author name
    description: Bogotano sumido en el sueño dogmático. B.S. in Aeronautics; Embry-Riddle Aeronautical University # Author description
    avatar: https://es.wahooart.com/Art.nsf/O/8YDVBA/$File/Juan-Gris-The-Smoker.JPG         # Author avatar
    slug: url           # Author profile slug
    url: url            # Author website URL
  Judge:
    name: David Jurado      # Author name
    description: Uno de los comediantes más queridos del país # Author description
    avatar: https://i.pinimg.com/originals/12/9d/c9/129dc96387803187a0fdb65b440f7748.jpg        # Author avatar
    slug: url           # Author profile slug
    url: url            # Author website URL
  Raf:
    name: Raf Pinewood      # Author name
    description: Autor Amateur # Author description
    avatar: https://vignette.wikia.nocookie.net/el-bestiario/images/e/ea/Dios_Cthulhu.png/revision/latest?cb=20150225025645&path-prefix=es        # Author avatar
    slug: url           # Author profile slug
    url: url            # Author website URL
  MoccaBM:
    name: Juan Diego Moncada
    description: Hic Sunt Dracones # Author description
    avatar: https://i.ebayimg.com/00/s/MTYwMFgxMTY2/z/vJkAAOSww1ljuOrh/$_57.JPG?set_id=880000500F        # Author avatar
    slug: url           # Author profile slug
    url: url            # Author website URL
  EnigmaPrime:
    name: Enigma Prime      # Author name
    description: Estudiante doctoral de física matemática en la Universidad Purdue # Author description
    avatar: https://heraldodemexico.com.mx/u/fotografias/fotosnoticias/2021/1/9/303160.jpg        # Author avatar

