authors:
  Chachalingo:
    name: Santiago Acuña González      # Author name
    description: Bogotano sumido en el sueño dogmático # Author description
    avatar: https://es.wahooart.com/Art.nsf/O/8YDVBA/$File/Juan-Gris-The-Smoker.JPG         # Author avatar
    slug: url           # Author profile slug
    url: url            # Author website URL
  Judge:
    name: David Jurado      # Author name
    description: Uno de los comediantes más queridos del pais # Author description
    avatar: https://i.pinimg.com/originals/12/9d/c9/129dc96387803187a0fdb65b440f7748.jpg        # Author avatar
    slug: url           # Author profile slug
    url: url            # Author website URL
  Raf:
    name: Raf Pinewood      # Author name
    description: Autor Amateur # Author description
    avatar: https://vignette.wikia.nocookie.net/el-bestiario/images/e/ea/Dios_Cthulhu.png/revision/latest?cb=20150225025645&path-prefix=es        # Author avatar
    slug: url           # Author profile slug
    url: url            # Author website URL
